### ISSUE TITLE
versionCode and updates

### ISSUE THREAD

**Issue by IzzySoft** [Koushikphy/Shared-Expense-Manager#2]
Please consider increasing `versionCode` whenever you preparing a release. Currently, all your `*.apk` have the very same `versionCode: 1` – which means Android internally considers them all to be the very same version, not announcing updates to users (`versionName` is just for display to the human eye). Thanks in advance!

**Comment by Koushikphy** [comment]
okay, added `version: 0.1.2+2` to `pubspec.yaml`.

**Comment by IzzySoft** [comment]
Thanks a lot, that was fast :smiley: Please remember also for future releases :stuck_out_tongue_winking_eye:
